'use strict';
const { createRobloxHttp } = require('./roblox-http');
const pluginRoot = require('node:path').resolve(__dirname, '..');
function createServices(ctx, config, options = {}) {
  const deps = { ctx, config, pluginRoot, robloxHttp: createRobloxHttp(ctx.http, config) };
  const install = factory => Object.defineProperties(deps, Object.getOwnPropertyDescriptors(factory(deps)));
  install(require('./features/platform'));
  install(require('./features/buttons'));
  install(require('./features/chat'));
  install(require('./features/storage-queue'));
  install(require('./features/roles'));
  install(require('./features/binding-tools'));
  install(require('./features/user-store'));
  install(require('./features/gift-code'));
  install(require('./features/music'));
  install(require('./features/operation-log'));
  install(require('./features/request-cache'));
  install(require('./features/transactions'));
  install(require('./features/points-store'));
  install(require('./features/levels'));
  install(require('./features/signin'));
  install(require('./features/query-billing'));
  install(require('./features/points'));
  install(require('./features/risk-rules'));
  install(require('./features/risk-store'));
  install(require('./features/violations'));
  install(require('./features/input-check'));
  install(require('./features/identity-check'));
  install(require('./features/output-audit'));
  install(require('./features/audit-queue'));
  install(require('./features/risk-admin'));
  install(require('./features/risk-control'));
  install(require('./features/audit-console'));
  install(require('./features/announcements'));
  install(require('./features/announcement-delivery'));
  install(require('./features/announcement-console'));
  install(require('./features/search-audit'));
  install(require('./features/market'));
  install(require('./features/result-format'));
  install(require('./features/server-render'));
  install(require('./features/catalog-render'));
  install(require('./features/chart-render'));
  install(require('./features/search-sessions'));
  install(require('./features/migration'));
  install(require('./features/guild-store'));
  install(require('./features/backup'));
  install(require('./features/api-adapter'));
  install(require('./features/legacy-ban'));
  install(require('./features/query-flow'));
  install(require('./features/search-display'));
  install(require('./features/permissions'));
  install(require('./features/media'));
  install(require('./features/image-audit'));
  install(require('./features/query-lock'));
  install(require('./features/bff-search'));
  install(require('./features/server-search'));
  install(require('./features/catalog-search'));
  install(require('./features/search-pagination'));
  install(require('./features/points-command-support'));
  install(require('./features/audit-command-support'));
  install(require('./features/migration-command-state'));
  install(require('./features/backup-command-state'));
  install(require('./features/user-query'));
  install(require('./features/group-query'));
  install(require('./features/game-query'));
  install(require('./features/relations-query'));
  install(require('./features/binding'));
  install(require('./features/legacy-signin'));
  if (options.register !== false) install(require('./features/button-events'));
  if (options.register !== false) install(require('./features/community'));
  if (options.register !== false) install(require('./features/lifecycle'));
  if (options.register !== false) install(require('./features/welcome'));
  if (options.register !== false) install(require('./features/announcement-hooks'));
  if (options.register !== false) install(require('./features/console-hooks'));
  if (options.register !== false) install(require('./features/commands/社群推荐'));
  if (options.register !== false) install(require('./features/commands/ROBLOX社群列表'));
  if (options.register !== false) install(require('./features/commands/报名推荐社群'));
  if (options.register !== false) install(require('./features/commands/刷新社群列表'));
  if (options.register !== false) install(require('./features/commands/我的信息'));
  if (options.register !== false) install(require('./features/commands/菜单'));
  if (options.register !== false) install(require('./features/commands/查看绑定'));
  if (options.register !== false) install(require('./features/commands/绑定Roblox账号'));
  if (options.register !== false) install(require('./features/commands/解除绑定'));
  if (options.register !== false) install(require('./features/commands/用户名搜索'));
  if (options.register !== false) install(require('./features/commands/用户ID搜索'));
  if (options.register !== false) install(require('./features/commands/群组名搜索'));
  if (options.register !== false) install(require('./features/commands/群组ID搜索'));
  if (options.register !== false) install(require('./features/commands/查询用户曾用名'));
  if (options.register !== false) install(require('./features/commands/获取用户头像'));
  if (options.register !== false) install(require('./features/commands/获取群组图标'));
  if (options.register !== false) install(require('./features/commands/游戏ID搜索'));
  if (options.register !== false) install(require('./features/commands/游戏名搜索'));
  if (options.register !== false) install(require('./features/commands/获取好友列表'));
  if (options.register !== false) install(require('./features/commands/获取粉丝列表'));
  if (options.register !== false) install(require('./features/commands/获取关注列表'));
  if (options.register !== false) install(require('./features/commands/游戏名精确搜索'));
  if (options.register !== false) install(require('./features/commands/添加管理员'));
  if (options.register !== false) install(require('./features/commands/删除管理员'));
  if (options.register !== false) install(require('./features/commands/给予风控限制'));
  if (options.register !== false) install(require('./features/commands/给予长期风控'));
  if (options.register !== false) install(require('./features/commands/解除风控限制'));
  if (options.register !== false) install(require('./features/commands/开启翻译'));
  if (options.register !== false) install(require('./features/commands/关闭翻译'));
  if (options.register !== false) install(require('./features/commands/绑定统计'));
  if (options.register !== false) install(require('./features/commands/服务器状态'));
  if (options.register !== false) install(require('./features/commands/签到'));
  if (options.register !== false) install(require('./features/commands/添加兑换码'));
  if (options.register !== false) install(require('./features/commands/查询兑换码'));
  if (options.register !== false) install(require('./features/commands/兑换码'));
  if (options.register !== false) install(require('./features/commands/积分排行榜'));
  if (options.register !== false) install(require('./features/commands/随机TOP音乐ID'));
  if (options.register !== false) install(require('./features/commands/积分'));
  if (options.register !== false) install(require('./features/commands/等级'));
  if (options.register !== false) install(require('./features/commands/兑换经验'));
  if (options.register !== false) install(require('./features/commands/流水'));
  if (options.register !== false) install(require('./features/commands/增减R点'));
  if (options.register !== false) install(require('./features/commands/增减经验'));
  if (options.register !== false) install(require('./features/commands/设定等级'));
  if (options.register !== false) install(require('./features/commands/违规添加'));
  if (options.register !== false) install(require('./features/commands/违规移除'));
  if (options.register !== false) install(require('./features/commands/调整风控等级'));
  if (options.register !== false) install(require('./features/commands/解除风控'));
  if (options.register !== false) install(require('./features/commands/风控状态'));
  if (options.register !== false) install(require('./features/commands/审核列表'));
  if (options.register !== false) install(require('./features/commands/审核处理'));
  if (options.register !== false) install(require('./features/commands/迁移至数据库'));
  if (options.register !== false) install(require('./features/commands/操作日志'));
  if (options.register !== false) install(require('./features/commands/数据预览'));
  if (options.register !== false) install(require('./features/commands/数据导出'));
  if (options.register !== false) install(require('./features/commands/数据导入'));
  Object.assign(deps.userLocal, deps.bindingMethods, deps.legacySigninMethods);
  return deps;
}
module.exports = { createServices };
